import Head from "next/head";
import styled from "styled-components";

const Title = styled.h1`
  font-size: ${(props) => props.theme.fontSize["xl"]};
  font-weight: 600;
  color: ${({ theme }) => theme.colors.teal};
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title>This is test for</Title>
      </main>
    </>
  );
}
