import PostDetail from "@/containers/PostDetail/PostDetail";
import Head from "next/head";

const PostDetailPage: React.FC = () => {
  return (
    <>
      <Head>
        <title>Post - Supermonos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostDetail />
    </>
  );
};

export default PostDetailPage;
